export const architectureProjects = [
  {
    id: "a1",
    src: "/project2.webp",
    title: "Eco-Tech Innovation Campus",
    location: "Bengaluru, India",
    year: "2024",
    area: "35,000 sq.m",
    category: "Architecture",
    description: "A sustainable research and development headquarters sculpted with mass timber glulam diagrids and passive solar shading fins.",
  },
  {
    id: "a2",
    src: "/project9.webp",
    title: "Civic Library & Cultural Archway",
    location: "Thiruvananthapuram, India",
    year: "2023",
    area: "12,000 sq.m",
    category: "Architecture",
    description: "A public library and cultural center built with porous laterite stone arches and natural daylit reading galleries.",
  },
  {
    id: "a3",
    src: "/project10.webp",
    title: "Tropical Water Courtyard Villa",
    location: "Alappuzha, Kerala",
    year: "2024",
    area: "850 sq.m",
    category: "Architecture",
    description: "A private contemporary residence organized around a central reflective water court with operable timber jali screens.",
  },
  {
    id: "a4",
    src: "/project4.webp",
    title: "Kochi Marine Civic Center",
    location: "Kochi, Kerala",
    year: "2023",
    area: "18,500 sq.m",
    category: "Architecture",
    description: "Civic maritime landmark featuring wave-inspired cantilevered roofs, terracotta louvers, and open breezeways.",
  },
];
