export const landscapeProjects = [
  {
    id: "l1",
    src: "/project1.webp",
    title: "Al Wasl Botanical Parkland",
    location: "Dubai, UAE",
    year: "2024",
    area: "120,000 sq.m",
    category: "Landscape",
    description: "An urban ecological oasis integrating arid-climate botanical gardens with regenerative stormwater retention lakes and shaded microclimatic walks.",
  },
  {
    id: "l2",
    src: "/project5.webp",
    title: "Creekside Mangrove Sanctuary",
    location: "Abu Dhabi, UAE",
    year: "2023",
    area: "85,000 sq.m",
    category: "Landscape",
    description: "Restoration of coastal mangrove wetlands with integrated pedestrian observation boardwalks and tidal flow channels.",
  },
  {
    id: "l3",
    src: "/landscape1.webp",
    title: "Coastal Waterfront Promenade",
    location: "Doha, Qatar",
    year: "2024",
    area: "45,000 sq.m",
    category: "Landscape",
    description: "A continuous 3.5km civic seaside promenade with native salt-tolerant trees, shaded pavilions, and ocean lookouts.",
  },
  {
    id: "l4",
    src: "/project7.webp",
    title: "Eco-Retreat Mountain Terraces",
    location: "Wayanad, India",
    year: "2023",
    area: "60,000 sq.m",
    category: "Landscape",
    description: "Terraced tea-estate landscapes restored with native rainforest species, organic agroforestry, and cascading rain gardens.",
  },
  {
    id: "l5",
    src: "/landscape2.webp",
    title: "Arid Botanical Innovation Garden",
    location: "Riyadh, Saudi Arabia",
    year: "2023",
    area: "160,000 sq.m",
    category: "Landscape",
    description: "A large-scale institutional botanical masterplan utilizing intelligent greywater recycling and drought-resilient vegetation palettes.",
  },
];
