import { Globe2, TreePine, Layers, ShieldCheck } from "lucide-react";

export const allTeam = [
  {
    id: "satish",
    name: "Satish Hiremath",
    role: "Managing Director",
    category: "leadership",
    image: "/team/satish.jpg",
    credentials: "B.Arch, Urban Systems",
    bio: "Over 20 years of architectural leadership directing large-scale civic masterplans, institutional developments, and ecological frameworks across India and the Middle East.",
    projects: "Al Wasl Botanical Parkland, South Bay Masterplan",
  },
  {
    id: "sarat",
    name: "T Sarat Chandra",
    role: "Head - BD & Strategic Advisory",
    category: "leadership",
    image: "/team/sarat.jpg",
    credentials: "M.Plan, Infrastructure Policy",
    bio: "Guiding institutional growth, government advisory frameworks, and strategic cross-border design partnerships across South Asia.",
    projects: "Smart City Infrastructure Frameworks",
  },
  {
    id: "kundan",
    name: "Kundan Kumar Thakur",
    role: "Lead – BD & Strategic Advisory",
    category: "leadership",
    image: "/team/kundan.jpg",
    credentials: "MBA, Urban Economics",
    bio: "Specializing in public-private urban partnerships, transit-oriented development policies, and feasibility modeling for infrastructure.",
    projects: "Kochi Marine Promenade Corridor",
  },
  {
    id: "nagraja",
    name: "Nagraja HR",
    role: "Lead - Technical Design",
    category: "technical",
    image: "/team/nagaraja.jpg",
    credentials: "B.Tech, Structural Integration",
    bio: "Directing multi-disciplinary BIM coordination, complex facade engineering, and precision construction documentation.",
    projects: "Eco-Tech Innovation Campus, BIM LOD 350",
  },
  {
    id: "setty",
    name: "N Setty",
    role: "Lead - Projects",
    category: "technical",
    image: "/team/setty.jpg",
    credentials: "Civil Engineering, PMP",
    bio: "Overseeing on-site quality assurance, contractor administration, and sustainable material compliance.",
    projects: "Wayanad Valley Eco-Lodge",
  },
  {
    id: "ramakrishna",
    name: "Ramakrishna T.S",
    role: "Lead – Technical Design",
    category: "technical",
    image: "/team/ramakrishna.jpg",
    credentials: "B.Arch, Building Physics",
    bio: "Expertise in passive solar envelope engineering, structural integration, and vernacular construction systems.",
    projects: "Cliffside Laterite Villa",
  },
  {
    id: "anagha",
    name: "Ar. Anagha",
    role: "AGM - Lead Architect",
    category: "design",
    image: "/team/anagha.jpg",
    credentials: "M.Arch (Sustainable Design)",
    bio: "Lead architect overseeing institutional masterplans, biophilic material systems, and complex architectural detailing.",
    projects: "Lumina Creative Atelier",
  },
  {
    id: "koushik",
    name: "Ar. Koushik Varma",
    role: "Lead - Landscape Architect",
    category: "design",
    image: "/team/koushik.jpg",
    credentials: "M.L.Arch (Landscape Ecology)",
    bio: "Specializing in civic parklands, sponge-city stormwater networks, and arid-climate botanical restoration.",
    projects: "Al-Barari Ecological Corridor",
  },
  {
    id: "shruthi",
    name: "Ar. Shruthi Laxmi",
    role: "DM - Sustainable Architect",
    category: "design",
    image: "/team/shruthi.jpg",
    credentials: "LEED AP, GRIHA Evaluator",
    bio: "Pioneering passive computational CFD modeling, thermal comfort simulations, and net-zero energy design frameworks.",
    projects: "Net-Zero Research Center",
  },
  {
    id: "indrajit",
    name: "Ar. Indrajit Koner",
    role: "Urban Planner",
    category: "design",
    image: "/team/indrajit.jpg",
    credentials: "M.Tech (Urban Planning)",
    bio: "Specializing in regional GIS territorial zoning, transit-oriented development corridors, and smart city infrastructure.",
    projects: "Bengaluru Smart City Corridor",
  },
  {
    id: "anand",
    name: "Ar. Anand Raj",
    role: "Senior Architect",
    category: "design",
    image: "/team/anand.jpg",
    credentials: "B.Arch, Tectonic Detailing",
    bio: "Directing architectural site execution, tectonic joinery detailing, and high-performance commercial envelopes.",
    projects: "Kochi Marine Civic Center",
  },
  {
    id: "swetha",
    name: "Ar. Swetha S",
    role: "Architect",
    category: "design",
    image: "/team/swetha.jpg",
    credentials: "B.Arch (Interior Architecture)",
    bio: "Focusing on tropical residential architecture, daylighting studies, and biophilic interior spaces.",
    projects: "Minimalist Coastal Penthouse",
  },
  {
    id: "balaji",
    name: "Ar. Balaji M",
    role: "Architect",
    category: "design",
    image: "/team/balaji.jpg",
    credentials: "B.Arch (Computational Design)",
    bio: "Expert in parametric modeling, BIM documentation, and modular prefabricated construction systems.",
    projects: "Mass Timber Glulam Structures",
  },
  {
    id: "godwin",
    name: "Godwin Leo",
    role: "Senior 3D Visualiser",
    category: "technical",
    image: "/team/godwin.jpg",
    credentials: "Architectural CGI Lead",
    bio: "Creating hyper-realistic architectural CGI visuals, computational light simulations, and cinematic studio animations.",
    projects: "Studio Cinematic Showcase",
  },
];

export const studioValues = [
  {
    title: "Radical Contextuality",
    desc: "Every design is rooted in the unique microclimate, geology, hydrology, and cultural heritage of its site.",
    icon: Globe2,
  },
  {
    title: "Biological Circularity",
    desc: "We prioritize renewable materials, closed-loop on-site water purification, and biodiversity restoration.",
    icon: TreePine,
  },
  {
    title: "Computational Rigor",
    desc: "BIM LOD 350 standards, wind CFD simulations, and solar path modeling ensure flawless precision.",
    icon: Layers,
  },
  {
    title: "Enduring Stewardship",
    desc: "We design structures and living landscapes meant to age gracefully and enrich generations of community life.",
    icon: ShieldCheck,
  },
];

export const milestones = [
  {
    year: "2018",
    title: "Studio Foundation",
    desc: "Established in Kerala as an integrated studio uniting landscape ecology and architecture.",
  },
  {
    year: "2021",
    title: "Regional Expansion",
    desc: "Commissioned for landmark civic waterfronts, sponge-city masterplans, and institutional campuses.",
  },
  {
    year: "2024",
    title: "International Recognition",
    desc: "Honored with major sustainability and urban design awards across South Asia and the Middle East.",
  },
  {
    year: "2026",
    title: "Net-Zero Practice",
    desc: "Pioneering mass timber glulam, bio-concrete sponge infrastructure, and 100% circular buildings.",
  },
];

export const teamFilterTabs = [
  { id: "all", label: "All Members" },
  { id: "leadership", label: "Leadership" },
  { id: "design", label: "Architects & Planners" },
  { id: "technical", label: "Technical & BIM" },
];
